/*
 * cmd_ger.h  -  german command options and description
 * 25.09.90
 *
 * 06.01.91 énderungen wg ls (jr)
 * 10.01.91 dito
 * 15.01.91 small commands: true false dirname basename
 *          file removed
 * 19.01.91 getopt
 * 23.01.91 runopts
 */
 
#ifndef _M_CMD_GER
#define _M_CMD_GER

#define OPT_alias	"[name [ersatz]]"
#define HLP_alias	"Aliase anzeigen, lîschen oder setzen"
#define OPT_backup	"[-icv] dateien"
#define HLP_backup	"Dateien kopieren, Neue Extension ist .bak"
#define OPT_basename	"zeichenkette [suffix]"
#define HLP_basename	"Dateiname aus vollem Pfad extrahieren"
#define OPT_blitmode	"[on|off]"
#define HLP_blitmode	"Blitter-Status anzeigen/Ñndern"
#define OPT_cat		"[-eilmnrstv] dateien"
#define HLP_cat		"dateien auf stdout anzeigen"
#define OPT_cd		"[dir]"
#define HLP_cd		"akt. Verzeichnis in dir oder $HOME wechseln"
#define OPT_chmod	"[-cv][[+-][ahsw]] dateien"
#define HLP_chmod	"Attribute setzen/lîschen"
#define OPT_cookie	""
#define HLP_cookie	"Cookie-Jar anzeigen"
#define OPT_cp		"[-cdrviasbnM] f1 f2  oder  cp f1..fn dir"
#define HLP_cp		"Dateien kopieren"
#define OPT_date	"[hhmm|mmddhhmm[yy]]"
#define HLP_date	"Systemdatum anzeigen/Ñndern"
#define OPT_df		"[-a][drv:...][dateien...]"
#define HLP_df		"Freien Disketten-Platz anzeigen"
#define OPT_dir		"[-adklmpqrstxABCFMRSUX1][-w zeichen][-I muster]"
#define HLP_dir		"Dateien anzeigen (sortiert, mehrspaltig)"
#define OPT_dirname	"[pfadname]"
#define HLP_dirname	"Ordnername aus vollem Pfad extrahieren"
#define OPT_dirs	""
#define HLP_dirs	"Directory-Stack anzeigen"
#define OPT_du		"[-acs][verzeichnis...]"
#define HLP_du		"Platzbedarf fÅr Verzeichnisse anzeigen"
#define OPT_echo	"[args]"
#define HLP_echo	"Argumente ausgeben"
#define OPT_env	"[var]"
#define HLP_env	"Environment-Variable anzeigen"
#define OPT_errorfile	"[-ap] datei"
#define HLP_errorfile	"stderr-Umlenkung setzen"
#define OPT_exit	"[wert]"
#define HLP_exit	"Mupfel beenden, wert bzw. 0 ist Exit-Status"
#define OPT_false	""
#define HLP_false	"Negativen Exit-Status setzen"
#define OPT_fkey	"[taste [text]]"
#define HLP_fkey	"Funktionstasten setzen/lîschen/anzeigen"
#define OPT_format	"[-vy][-s seiten][-c sektoren][-l label] drv:"
#define HLP_format	"Diskette formatieren"
#define OPT_free	"[-l]"
#define HLP_free	"Freien Speicher anzeigen"
#define OPT_getopt	"legale-Optionen Optionen"
#define HLP_getopt	"Optionen testen und auflîsen"
#define OPT_hash	"[-r][-d dir]"
#define HLP_hash	"Hash-Tabelle anzeigen/lîschen"
#define OPT_help	"[cmd]"
#define HLP_help	"Liste aller Kommandos oder Hilfe zu cmd"
#define OPT_init	"[-y][-s seiten][-c sektoren][-l label] drv:"
#define HLP_init	"Schnell-Lîschen einer Diskette"
#define OPT_kbrate	"[-i wartezeit][-r wiederholfrq]"
#define HLP_kbrate	"Tastatur-Einstellung"
#define OPT_kclick	"[on|off]"
#define HLP_kclick	"Tastenklick-Einstellung"
#define OPT_label	"[drive [label]]"
#define HLP_label	"Label anzeigen/Ñndern"
#define OPT_ls		"[-adklmpqrstxABCFMRSUX1][-w zeichen][-I muster]"
#define HLP_ls		"Dateien anzeigen (sortiert)"
#define OPT_mkdir	"[-p] dirs"
#define HLP_mkdir	"Directories anlegen"
#define OPT_more	"dateien"
#define HLP_more	"datei-Inhalt durchblÑttern"
#define OPT_mv		"[-cvib] f1 f2 oder mv f1..fn dir oder mv dir1 dir2"
#define HLP_mv		"dateien umbenennen/verschieben"
#define OPT_noalias	"kommando"
#define HLP_noalias	"kommando 'wîrtlich' ausfÅhren"
#define OPT_pause	"[args]"
#define HLP_pause	"argumente ausgeben, auf Tastendruck warten"
#define OPT_popd	""
#define HLP_popd	"cd ins letzte gemerkte Verzeichnis"
#define OPT_print	"[-f][-l zeilen][-t tab-weite] dateien"
#define HLP_print	"dateien ausdrucken"
#define OPT_prtconf	"[-wmcbealdrpsf]"
#define HLP_prtconf	"Parallel-Schnittstelle einstellen"
#define OPT_pushd	"[dir]"
#define HLP_pushd	"dir bzw . auf Directory-Stack speichern"
#define OPT_pwd	"[-a|drv:]"
#define HLP_pwd	"aktuelles Verzeichnis ausgeben"
#define OPT_rename	"[-icv] ext dateien"
#define HLP_rename	"dateien umbenennen"
#define OPT_rm		"[-rfivb] dateien"
#define HLP_rm		"dateien lîschen"
#define OPT_rmdir	"dirs"
#define HLP_rmdir	"directories lîschen"
#define OPT_rsconf	"[-b baudrate][-xrn][-p paritÑt][-s stopbits][-c bits/zchn]"
#define HLP_rsconf	"Serielles Interface einstellen"
#define OPT_runopts	"[-csv][-t tpasiz][[+-][flm]] dateien"
#define HLP_runopts	"Optionen fÅr Programmtyp setzen"
#define OPT_set	"[var [value]]"
#define HLP_set	"Interne Variable setzen/lîschen/anzeigen"
#define OPT_setenv	"[var [value]]"
#define HLP_setenv	"Environment-Variable setzen/lîschen/anzeigen"
#define OPT_setscrap	"[-fq] [dir]"
#define HLP_setscrap	"AES Scrap-Pfad anzeigen/setzen"
#define OPT_show	"var"
#define HLP_show	"Environment-Variable anzeigen"
#define OPT_shrink	"[-b val][-t val][-f][-i]"
#define HLP_shrink	"Speicher verkleinern/freigeben"
#define OPT_test	"ausdruck"
#define OPT_testk	"ausdruck ]"
#define HLP_test	"Bedingung testen"
#define OPT_timer	"[-s]"
#define HLP_timer	"Timer starten/anzeigen"
#define OPT_touch	"[-c][-d hhmm|mmddhhmm[yy]] dateien"
#define HLP_touch	"Modifikationsdatum Ñndern"
#define OPT_tree	"[-di][-p pfad][-f muster]"
#define HLP_tree	"Datei-Hierarchie anzeigen"
#define OPT_true	""
#define HLP_true	"Positiven Exit-Status setzen"
#define OPT_vdir	"[-adklmpqrstxABCFMRSUX1][-w zeichen][-I muster]"
#define HLP_vdir	"Dateien anzeigen (sortiert, ausfÅhrlich)"
#define OPT_version	"[-amgdth]"
#define HLP_version	"Versionsnummern anzeigen"
#define OPT_whereis	"kommando"
#define HLP_whereis	"kommando in $PATH etc suchen"

#define OPT_empty	""
#define HLP_empty	"leeres Kommando"

#endif