/*
 * cmd_eng.h  -  english command options and description
 * 04.06.90
 */
 
#ifndef _M_CMD_ENG
#define _M_CMD_ENG

#define OPT_alias	"[name [replacement]]"
#define HLP_alias	"show, set or unset alias"
#define OPT_backup	"[-icv] files"
#define HLP_backup	"copy files, dest extension is .bak"
#define OPT_basename	"string [suffix]"
#define HLP_basename	"deliver filename portion of string"
#define OPT_blitmode	"[on|off]"
#define HLP_blitmode	"show or set blitter status"
#define OPT_cat	"[-eilmnrstv] files"
#define HLP_cat	"print files on stdout"
#define OPT_cd		"[dir]"
#define HLP_cd		"change directory to dir or $HOME"
#define OPT_chmod	"[-cv][[+-][ahsw]] files"
#define HLP_chmod	"set/clear attributes"
#define OPT_cookie	""
#define HLP_cookie	"display cookie jar contents"
#define OPT_cp		"[-cvdriasbn] f1 f2 or cp f1..fn dir"
#define HLP_cp		"copy files"
#define OPT_date	"[hhmm|mmddhhmm[yy]]"
#define HLP_date	"display or set system date and time"
#define OPT_df		"[-a][drv:...][files...]"
#define HLP_df		"display free disk space"
#define OPT_dir		"[-adklmpqrstxABCFMRSUX1][-w columns][-I pattern]"
#define HLP_dir		"list files (sorted, multi-column)"
#define OPT_dirname	"[string]"
#define HLP_dirname	"deliver path portion of string"
#define OPT_dirs	""
#define HLP_dirs	"display directory stack"
#define OPT_du		"[-acs][dirnames...]"
#define HLP_du		"show disk usage for directories"
#define OPT_echo	"[args]"
#define HLP_echo	"print args on stdout"
#define OPT_env	"[var]"
#define HLP_env	"display environment variable"
#define OPT_errorfile	"[-ap] file"
#define HLP_errorfile	"set stderr redirection"
#define OPT_exit	"[val]"
#define HLP_exit	"terminate mupfel, return val or 0 to caller"
#define OPT_false	""
#define HLP_false	"return non-zero exit code"
#define OPT_fkey	"[key [str]]"
#define HLP_fkey	"display or define function keys"
#define OPT_format	"[-yv][-s sides][-c sectors][-l label] drv:"
#define HLP_format	"format disk"
#define OPT_free	"[-l]"
#define HLP_free	"display free main memory"
#define OPT_getopt	"legal-args options..."
#define HLP_getopt	"parse argument line"
#define OPT_hash	"[-r][-d dir]"
#define HLP_hash	"display, remove or enter programs in dir into hash table"
#define OPT_help	"[cmd]"
#define HLP_help	"print list of commands or help for cmd"
#define OPT_init	"[-y][-s sides][-c sectors][-l label] drv:"
#define HLP_init	"fast disk erase"
#define OPT_kbrate	"[-i initial][-r repeat]"
#define HLP_kbrate	"set keyboard options"
#define OPT_kclick	"[on|off]"
#define HLP_kclick	"set key click"
#define OPT_label	"[drive [label]]"
#define HLP_label	"show or change label on drive"
#define OPT_ls		"[-adklmpqrstxABCFMRSUX1][-w columns][-I pattern]"
#define HLP_ls		"list files (sorted, multi-column)"
#define OPT_mkdir	"[-p] dirs"
#define HLP_mkdir	"create directories"
#define OPT_more	"files"
#define HLP_more	"page through files"
#define OPT_mv		"[-cvib] f1 f2 or mv f1..fn dir or mv dir1 dir2"
#define HLP_mv		"rename/move files"
#define OPT_noalias	"command"
#define HLP_noalias	"execute command verbatim"
#define OPT_pause	"[args]"
#define HLP_pause	"echo args if any, wait for keypress"
#define OPT_popd	""
#define HLP_popd	"change dir to last pushed directory"
#define OPT_print	"[-f][-l lines][-t tabsize] files"
#define HLP_print	"print the given files"
#define OPT_prtconf	"[-wmcbealdrbsf]"
#define HLP_prtconf	"set parallel interface"
#define OPT_pushd	"[dir]"
#define HLP_pushd	"save dir or . on directory stack"
#define OPT_pwd	"[-a|drv:]"
#define HLP_pwd	"print working directory"
#define OPT_rename	"[-icv] ext files"
#define HLP_rename	"bulk file rename"
#define OPT_rm		"[-rvfib] files"
#define HLP_rm		"remove files"
#define OPT_rmdir	"dirs"
#define HLP_rmdir	"remove directories (must be empty)"
#define OPT_rsconf	"[-b baudrate][-xrn][-p parity][-s stopbits][-c char. size]"
#define HLP_rsconf	"set serial interface"
#define OPT_runopts	"[-csv][-t tpasiz][[+-][flm]] files"
#define HLP_runopts	"set options for executables"
#define OPT_set	"[var [value]]"
#define HLP_set	"show, set or unset internal variables"
#define OPT_setenv	"[var [value]]"
#define HLP_setenv	"set or unset environment variable"
#define OPT_setscrap	"[-fq] [dir]"
#define HLP_setscrap	"show or set AES scrap path"
#define OPT_show	"var"
#define HLP_show	"display environment variable"
#define OPT_shrink	"[-b val][-t val][-f][-i]"
#define HLP_shrink	"shrink/free memory"
#define OPT_test	"expr"
#define OPT_testk	"expr ]"
#define HLP_test	"test condition"
#define OPT_timer	"[-s]"
#define HLP_timer	"start/display timer"
#define OPT_touch	"[-c][-d hhmm|mmddhhmm[yy]] files"
#define HLP_touch	"set file modification time"
#define OPT_tree	"[-di][-f filespec][-p path]"
#define HLP_tree	"display file hierarchy"
#define OPT_true	""
#define HLP_true	"return zero exit code"
#define OPT_vdir	"[-adklmpqrstxABCFMRSUX1][-w columns][-I pattern]"
#define HLP_vdir	"list files (sorted, long-format)"
#define OPT_version	"[-amgdth]"
#define HLP_version	"display version numbers"
#define OPT_whereis	"cmd"
#define HLP_whereis	"locate cmd in $PATH"
#define OPT_empty	""
#define HLP_empty	"empty command"

#endif