/*
 * msg_eng.h  -  english messages for Mupfel
 * 27.01.91
 */
 
#ifndef _M_MSG_ENG
#define _M_MSG_ENG

#define AL_CANTSET	"can't set alias for '%s'"
#define AL_UNDEF	"%s not defined"

#define BT_ERROR	"read or seek error on %s"
#define BT_STARTUP	"can't open startup file %s"

#define BL_STATUS	"blitter is %s"
#define BL_ON		"on"
#define BL_OFF		"off"
#define BL_NOBLIT	"no blitter installed"

#define CA_CANTOPEN	"can't open %s"
#define CA_CANTREAD	"can't read from %s"
#define CA_CANTWRT	"can't write to standard output"
#define CA_DIRECT	"end of input: UNDO or CTRL-Z"

#define CD_NOCD	"Sorry, can't change directory from MUPFEL.MUP"
#define CD_TOOBAD	"Too bad"
#define CD_NOHOME	"HOME not set"
#define CD_NOEMPTY	"empty directory name not allowed"
#define CD_MANYARGS	"more than one directory name given"
#define CD_BADDIR	"%s: bad directory"
#define CD_MANYPUSH	"too many pushes"
#define CD_NOPOP	"nothing on stack"
#define CD_BADPOP	"%c:%s: bad directory"
#define CD_NOSTACK	"directory stack empty"
#define CD_NODRV	"%s is not a drive specifier"

#define CH_ISDIR	"%s is a directory"
#define CH_NOFILE	"%s: no such file"
#define CH_CANTOPEN	"can't open %s"
#define CH_GETATTR	"can't get attributes for %s"
#define CH_SETATTR	"can't set attributes for %s"
#define CH_ILLOPT	"illegal option %c"
#define CH_ILLOPTST	"illegal option %s"

#define CK_DAMAGE	"The executed program damaged %s. Be careful!"
#define CK_OK		"Continue"
#define CK_REBOOT	"Reboot"

#define CO_HEADER	"cookie  value"
#define CO_NOCOOKIE	"no cookie jar installed"

#define CP_USAGE	"usage"
#define CP_INDENT	"     "
#define CP_CONFCP	"%s: %s already exists. overwrite (y/n/a/q)? "
#define CP_CHOICE	"YNAQ"
#define CP_ASKCP	"%s: copy %s to %s (y/n/a/q)? "
#define CP_SHOWCP	"%s %s to %s ..."
#define CP_COPYING	"copying"
#define CP_MOVING	"moving"
#define CP_ENDSEC	" done.\nrenaming %s to %s ..."
#define CP_OVERWRT	"can't overwrite %s"
#define CP_FULLDISK	"target disk is full"
#define CP_WRITEERR	"write error on %s"
#define CP_READERR	"read error on %s"
#define CP_DUPFILE	"duplicate filename %s"
#define CP_NOMEM	"not enough memory"
#define CP_CANTCRT	"can't create %s"
#define CP_CPDIR	"can't copy directory %s"
#define CP_CANTOPEN	"can't open %s"
#define CP_CPDONE	" done."
#define CP_NOFILE	"%s: no such file"
#define CP_READONLY	"%s is read-only"
#define CP_RENAME	"can't rename %s to %s"
#define CP_RECUR	"use -r to copy directories"
#define CP_NEED14	"need TOS 1.4 to rename directories"
#define CP_ARCHWARN	"WARNING: -a doesn't work correctly with TOS 1.0 or 1.2"
#define CP_NODIR	"%s: %s: not a directory"
#define CP_EXTERR	"ext must be 1 to 3 chars"
#define CP_RENAMDIR	"can't rename directory %s"
#define CP_EXISTS	"%s already exists"
#define CP_BACKUP	"can't backup directory %s"

#define CT_ILLBAUD	"illegal baud rate"
#define CT_ILLPAR	"value for -p must be e, o or n"
#define CT_ILLCS	"value for -c must be 5-8"
#define CT_ILLSTOP	"value for -s must be 1-3"
#define CT_PRTCONF	"printer configuration:"
#define CT_PRINTER	" printer"
#define CT_DAISY	"daisywheel"
#define CT_DOTMAT	"dot matrix"
#define CT_COLOR	"color"
#define CT_MONO	"monochrome"
#define CT_EPSON	"epson"
#define CT_ATARI	"atari"
#define CT_LQ		"letter quality"
#define CT_DRAFT	"draft"
#define CT_RS232	"rs232"
#define CT_CENTR	"centronics"
#define CT_SINGLE	"single"
#define CT_FANFOLD	"fanfold"
#define CT_KBRATE	"initial delay = %d ms, repeat delay = %d ms"
#define CT_KBARG	"argument not numeric or zero"
#define CT_KEYCLICK	"keyclick is %s"
#define CT_KCON	"on"
#define CT_KCOFF	"off"

#define DF_NOINFO	"can't get info about drive %c:"
#define DF_INFO		"Drive             KBytes    used   avail  capacity  mounted from"
#define DF_NODRIVE	"drive %c: not available"
#define DF_NOLABEL	"no label"
#define DF_BADFILE	"bad filename `%s'"

#define DT_BADSPEC	"bad date specifier"
#define DT_NEWDATE	"New date: %s"
#define DT_BADCONV	"bad date conversion"
#define DT_ISDIR	"%s: is a directory"
#define DT_CANTCRT	"%s: can't create"
#define DT_CANTSET	"can't set time for %s"
#define DT_NONEXIST	"%s doesn't exist"

#define DU_NOMEM	"out of memory"
#define DU_ILLFILE	"`%s' not found"

#define EC_PRESSCR	"Press RETURN: "

#define EF_CANTCRT	"can't create %s"
#define EF_ISRO		"%s is write protected"
#define EF_STATUS	"error output is redirected to %s"
#define EF_NOFILE	"error output is not redirected"

#define ET_NOEXIT	"No exit. Close this window to leave the console."

#define EV_ILLNAME	"illegal name %s"
#define EV_ILLVAR	"illegal var %s"
#define EV_CANTSET	"can't set %s"
#define EV_NOTSET	"%s not set"

#define EX_RUNNER	"Where is RUNNER.APP?"
#define EX_CANTRUN	"Sorry, can't run programs from MUPFEL.MUP"
#define EX_TOOBAD	"Too bad"
#define EX_BADCD	"Can't chdir to %s!"
#define EX_OOPS	"Oops!"
#define EX_USEXARG	"arg list too long, using xArg/ARGV"
#define EX_PRESSCR	"Press RETURN..."
#define EX_CANTEXEC	"can't exec %s"
#define EX_NOMEM	"not enough memory for %s"
#define EX_NOTTOS	"%s: not a TOS executable"
#define EX_CRASH	"%s crashed! If you continue, keep your fingers crossed."
#define EX_OK		"Continue"
#define EX_REBOOT	"Reboot"

#define FB_NOMEM	"%s: not enough memory for %s"
#define FB_READERR	"%s: read error on %s"

#define FK_ILLKEY	"illegal function key"

#define FM_NOROOM	"no room for track buffer"
#define FM_INFO	"formatting track %02d side %d"
#define FM_FMTERR	"error formatting track %d:"
#define FM_ABORT	"aborted"
#define FM_WRTBOOT	"can't write boot sector on %c:"
#define FM_WRTFAT	"can't write root dir/FAT on %c:"
#define FM_ILLSECS	"only 9 or 10 sectors allowed"
#define FM_ILLDRV	"can't format drive %c:"
#define FM_CONFIRM	"really format disk in drive %c: (y/n)? "
#define FM_CHOICE	"YN"
#define FM_WRTLBL	"can't write label on %c:"

#define FR_FRAG	"memory too fragmented"
#define FR_HEADER	"blk address    size"
#define FR_INFO	"%lu bytes (%luK) free in %d blocks, largest block: %lu bytes (%luK)"

#define GM_NOVDI	"%s: no vdi workstation available, aborting"
#define GM_NOAES	"%s: appl_init() failed, aborting"
#define GM_NOAUTO	"You can't run %s from your AUTO folder!"

#define GO_AMBIG	"%s: option '%s' is ambigious"
#define GO_NOARG	"%s: option '%c%s' doesn't allow an argument"
#define GO_REQARG	"%s: option '%s' requires an argument"
#define GO_REQARG2	"%s: option '-%c' requires an argument"
#define GO_ILLOPT	"%s: unrecognized option '%c%s'"
#define GO_ILLOPT2	"%s: unrecognized option, character code 0%o"
#define GO_ILLOPT3	"%s: unrecognized option '-%c'"
#define GO_OOMEMORY	"%s: not enough memory"

#define HA_OPTERR	"can't combine -r with -d"
#define HA_NODIR	"%s: not a directory"
#define HA_TITLE	"hits  cost  cmd        full path"

#define HE_NOCMD	"not a mupfel builtin"

#define HI_CRTERR	"Can't create history file!"
#define HI_WRTERR	"Write error on history file!"

#define IN_WRTBOOT	"can't write boot sector on %c"
#define IN_WRTERR	"write error on %c:"
#define IN_ILLSECS	"only 9 or 10 sectors allowed"
#define IN_ILLDRV	"can't init drive %c:"
#define IN_CONFIRM	"really initialize disk in drive %c: (y/n)? "
#define IN_CHOICE	"YN"
#define IN_READERR	"can't read boot sector from drive %c:"
#define IN_NONTOS	"non-TOS disk. Please specify sides and sectors."

#define LB_NODRV	"drive %c: not available"
#define LB_VOLNAME	"volume in drive %c: is %s"
#define LB_NOLBL	"volume in drive %c: has no label"
#define LB_ILLLBL	"illegal label"
#define LB_EXISTS	"file or dir %s already exists"
#define LB_RMLBL	"can't remove old label"
#define LB_CANTSET	"can't set label on drive %c:"

#define LE_CMDHIST	"Command history:"

#define LO_NOMEM	"out of memory"

#define LS_NOFILE	"%s: no such file or directory"
#define LS_WRONGW	"wrong column count"
#define LS_NOMEM	"not enough memory"
#define LS_NOMEMD	"not enough memory for %s"

#define MA_TOOLONG	"arg list too long"
#define MA_ILLREDIR	"illegal null redirection"
#define MA_EOF		"EOF or newline unexpected"
#define MA_ALOOP	"endless alias loop detected"
#define MA_QUOTE	"unmatched quote %c"

#define MK_EXISTS	"%s already exists"
#define MK_CANTCRT	"%s: can't create"

#define MO_INFO	"%s: line %ld of %ld (%d%%), %lu bytes"
#define MO_CANTOPEN	"can't open %s"
#define MO_ISTTY	"can't read from CON: or AUX:"
			    /*         1         2         3         4         5         6         7         8*/
			    /*12345678901234567890123456789012345678901234567890123456789012345678901234567890*/
#define MO_HELP	"Dn:CR, Up:K,|PgDn:SP,F PgUp:BS,B|Nxt:N Prv:P|Xit:ESC,Q|Info: ^G|Srch: /,?,A"

#define MU_WRONGTOS	"Sorry, %s won't work with TOS releases below 1.02"
#define MU_TOOBAD	"Too bad"

#define MI_IOFMT 	"%s%sI/O error %d%s%s\n"
#define MI_IOACC	" accessing "
#define MI_USAGE	"usage"
#define MI_OPTIONS	"character options can be replaced by words:"

#define PA_NOFILE	"%s: no such file or directory"
#define PA_NODRV	"drive %c: not available"
#define PA_NOTFOUND	"%s: not found"

#define PR_NORESP	"printer is not responding"
#define PR_CANTOPEN	"can't open %s"

#define RD_CANTMOD	"can't modify existing %s"
#define RD_CANTCRT	"can't create %s"
#define RD_ISRO	"%s is read-only"
#define RD_CANTOPEN	"can't open %s"

#define RM_SHOWRMD	"removing dir %s ..."
#define RM_ISFILE	"%s is not a directory"
#define RM_NODIR	"%s: no such directory"
#define RM_ILLDIR	"can't remove directory '%s'"
#define RM_NOTEMPTY	"%s: not empty"
#define RM_INTRN	"%s: GEMDOS internal error -65"
#define RM_DONE	" done."
#define RM_CONFIRM	"remove %s (y/n/a/q)? "
#define RM_CHOICE	"YNAQ"
#define RM_SHOWRM	"removing %s ..."
#define RM_ISDIR	"can't remove directory %s"
#define RM_NOFILE	"%s: no such file"
#define RM_CANTRM	"%s: can't remove (read-only?)"

#define RN_IOERR	"I/O error accessing %s"
#define RN_NOVWK	"[1][Can't open workstation][Argh]"
#define RN_NOARGS	"[1][RUNNER requires arguments!][OK]"
#define RN_CANTEXEC "Can't exec %s"
#define RN_NOMEM	"Not enough memory for %s"
#define RN_NOPGM	"%s: not a TOS executable"
#define RN_LOADERR	"I/O error loading %s"

#define RO_NOTEXEC	"%s: not a TOS executable"
#define RO_ISDIR	"%s is a directory"
#define RO_NOFILE	"can't open %s"
#define RO_CANTOPEN	"can't open %s"
#define RO_READHDR	"%s: can't read header"
#define RO_WRITEHDR	"%s: can't write header"
#define RO_ILLOPT	"invalid option %c"
#define RO_ILLOPTST	"invalid option %s"
#define RO_ILLSIZE	"tpa size %s not numeric"
#define RO_OUTRANGE	"invalid tpa size %s"
#define RO_NOTPA	"tpa size missing"

#define SC_CANTGET	"can't get scrap path"
#define SC_CURRSCRP	"current scrap path is %s"
#define SC_NOSCRP	"scrap path not set"
#define SC_OLDSCRP	"scrap path already set to %s"
#define SC_ABSPATH	"need absolute path"
#define SC_NODIR	"%s: no such directory"
#define SC_CANTSET	"can't set scrap path"

#define SV_NOTSET	"not set"
#define SV_ILLVAR	"illegal var"

#define SK_MFREE	"Mfree() error!"
#define SK_CNTALLOC	"can't alloc %lu bytes"
#define SK_NOSHRINK	"can't shrink by more than is free!"
#define SK_BUYRAM	"you should buy a RAM expansion!"
#define SK_NOTSHRNK	"memory is not shrinked"
#define SK_SHRINKBY	"memory is shrinked by %lu bytes (%luK)"
#define SK_FREE	", free memory: %lu bytes (%luK)"
#define SK_ILLSIZE	"illegal size specifier"
#define SK_BADARG	"argument not numeric or zero"
#define SK_ARGUSE	"only one of -b, -t, -f or -i allowed"

#define	TE_ARGEXP	"argument expected"
#define TE_ARGEXPF	"argument expected, found %s"
#define TE_INTEXP	"integer expression expected %s"
#define TE_BEFORE	"before"
#define TE_AFTER	"after"
#define TE_MISSBR	"missing `]'"
#define TE_TOOMANY	"too many arguments"
#define TE_NTL		"-nt does not accept -l"

#define TI_TIME		"elapsed time: "

#define TR_DONE	" done."
#define TR_INFO	"%s: %ld byte(s), %d file(s), %d folder(s)"
#define TR_FIND	"%s: not a directory"
#define TR_HASH	"unable to normalize %s"

#define VE_VERSION	"version"
#define VE_HARDDISK	"Hard disk driver version"
#define VE_NOTACC	"is not accessible."
#define VE_NOHARD	"No hard disk driver installed."

#define WH_HASHED	"%s is hashed (%s)"
#define WH_IS		"%s is %s"
#define WH_ALIAS	"%s is an alias for '%s'"
#define WH_BUILTIN	"%s is a mupfel builtin"
#define WH_NOTFOUND	"%s: not found"

#endif